[package]
name = "gzify"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.30", features = ["derive"]}
env_logger = "0.11.6"
flate2 = "1.0.35"
indicatif = "0.17.11"
log = "0.4.25"
